---
sample_rate: 44100
clip_duration: 10.
max_caption_len: 100

train_datasets:
    GTZAN:
        root: "/Brain/public/datasets/gtzan"
        split: "train"
        test_fold: 0

test_datasets:
    GTZAN:
        root: "/Brain/public/datasets/gtzan"
        split: "test"
        test_fold: 0
        
audio_codec:
    name: DAC
    n_quantizers: 2

tokenizer:
    name: BertDAC

llm:
    name: Llama
    trainable: True
    block_size: 2048  # Maximize block size
    vocab_size:  # Leave blank. Parsed later from len(tokenier)
    n_layer: 12
    n_head: 12
    n_embd: 768
    
train:
    device: "cuda"
    num_workers: 8
    loss: ce_loss
    optimizer: AdamW
    lr: 1e-4
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 16
    test_every_n_steps: 250
    save_every_n_steps: 5000
    training_steps: 25000
    resume_ckpt_path:  # Leave blank if train from scratch
